apiVersion: v1
kind: Service
metadata:
  name: nginx-front
  namespace: nginx-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-front
  type: NodePort
