apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/FrenchyMike/ArgoCD-KK.git
    targetRevision: HEAD
    path: ./declarative/manifests/nginx
   
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx

  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
